In [1]:
import pandas as pd

df = pd.read_csv("../datasets/raw/ufc-master.csv")

In [2]:
import os
import sys

PROJECT_ROOT = os.path.abspath("..")

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import setup_notebook

✅ GladiatorAI Environment Ready
Project Root: c:\Users\user\GladiatorAI

In [3]:
from feature_engine.history import HistoryEngine
from feature_engine.calculators.record import RecordEngine

history_engine = HistoryEngine(df)

record_engine = RecordEngine()

In [4]:
history = history_engine.get_history(

    fighter="Sean O'Malley",

    before_date="2025-01-01"
)

record = record_engine.build(

    history,

    "Sean O'Malley"
)

record

RecordStats(wins=10, losses=2, draws=0, no_contests=0, total_fights=12, win_rate=0.833)

In [5]:
history = history_engine.get_history(

    fighter="Merab Dvalishvili",

    before_date="2025-01-01"
)

record = record_engine.build(

    history,

    "Merab Dvalishvili"
)

record

RecordStats(wins=11, losses=2, draws=0, no_contests=0, total_fights=13, win_rate=0.846)

In [6]:
from feature_engine.calculators.physical import PhysicalEngine

physical_engine = PhysicalEngine()

In [7]:
from feature_engine.calculators.momentum import MomentumEngine

momentum_engine = MomentumEngine()

In [8]:
history = history_engine.get_history(

    fighter="Sean O'Malley",

    before_date="2025-01-01"
)

momentum = momentum_engine.build(

    history,

    "Sean O'Malley"
)

momentum

MomentumStats(current_win_streak=0, current_lose_streak=1, last_five_win_rate=0.8, momentum_score=-1.0)

In [9]:
from feature_engine.calculators import ActivityEngine

activity_engine = ActivityEngine()

In [10]:
history = history_engine.get_history(

    fighter="Sean O'Malley",

    before_date="2025-01-01"

)

activity = activity_engine.build(

    history,

    snapshot_date="2025-01-01"

)

activity

ActivityStats(days_since_last_fight=109, fights_last_year=2)

In [11]:
df["finish"].value_counts()

finish
U-DEC         2681
KO/TKO        2223
SUB           1260
S-DEC          699
M-DEC           52
DQ              18
CNC              3
Overturned       3
Name: count, dtype: int64

In [12]:
from feature_engine.calculators.finishing import FinishingEngine
finishing_engine = FinishingEngine()

history = history_engine.get_history(
    fighter="Sean O'Malley",
    before_date="2025-01-01"
)

finishing = finishing_engine.build(
    history,
    "Sean O'Malley"
)

finishing

FinishingStats(ko_wins=6, submission_wins=0, decision_wins=4, finish_rate=0.6, ko_rate=0.6, submission_rate=0.0, decision_rate=0.4)

In [13]:
import feature_engine.constants as c

print(c.__file__)
print(hasattr(c, "FINISH"))

print(dir(c))

c:\Users\user\GladiatorAI\feature_engine\constants.py
True
['B_AGE', 'B_FIGHTER', 'B_HEIGHT', 'B_LOSE_STREAK', 'B_LOSSES', 'B_REACH', 'B_SIG_ACC', 'B_SIG_STR', 'B_SUB', 'B_TD', 'B_TD_ACC', 'B_WINS', 'B_WIN_STREAK', 'DATE', 'FINISH', 'R_AGE', 'R_FIGHTER', 'R_HEIGHT', 'R_LOSE_STREAK', 'R_LOSSES', 'R_REACH', 'R_SIG_ACC', 'R_SIG_STR', 'R_SUB', 'R_TD', 'R_TD_ACC', 'R_WINS', 'R_WIN_STREAK', 'TOTAL_FIGHT_TIME', 'WINNER', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']

In [14]:
[c for c in df.columns if "SIG" in  c]

['B_avg_SIG_STR_landed',
 'B_avg_SIG_STR_pct',
 'R_avg_SIG_STR_landed',
 'R_avg_SIG_STR_pct']

In [15]:
[c for c in df.columns if "pct" in c.lower()]

['B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_avg_SIG_STR_pct', 'R_avg_TD_pct']

In [16]:
from feature_engine.calculators import StrikingEngine

striking_engine = StrikingEngine()

history = history_engine.get_history(

    fighter="Sean O'Malley",

    before_date="2025-01-01"

)

striking = striking_engine.build(

    history,

    "Sean O'Malley"

)

striking

StrikingStats(average_sig_strikes=6.7, strike_accuracy=0.61, strike_defence=0.0, strike_differential=0.0)

In [17]:
from feature_engine.calculators import GrapplingEngine

grappling_engine = GrapplingEngine()

history = history_engine.get_history(

    fighter="Sean O'Malley",

    before_date="2025-01-01"
)

grappling = grappling_engine.build(

    history,

    "Sean O'Malley"
)

grappling

GrapplingStats(average_takedowns=0.29, takedown_accuracy=0.42, takedown_defence=0.0, average_submission_attempts=0.3)

In [18]:
from feature_engine.calculators import DurabilityEngine

durability_engine = DurabilityEngine()

history = history_engine.get_history(

    fighter="Sean O'Malley",

    before_date="2025-01-01"

)

durability = durability_engine.build(

    history
)

durability

DurabilityStats(average_fight_time=744.2, average_sig_strikes_absorbed=0.0)

In [19]:
from feature_engine.history import HistoryEngine
from feature_engine.profile import ProfileEngine


history_engine = HistoryEngine(df)

profile_engine = ProfileEngine()

In [20]:
history = history_engine.get_history(

    fighter="Sean O'Malley",

    before_date="2025-01-01"
)

profile = profile_engine.build(

    history,

    fighter="Sean O'Malley",

    snapshot_date="2025-01-01"
)

profile

PreFightProfile(fighter="Sean O'Malley", snapshot_date=Timestamp('2025-01-01 00:00:00'), physical=PhysicalStats(age=29.0, height=180.34, reach=182.88), record=RecordStats(wins=10, losses=2, draws=0, no_contests=0, total_fights=12, win_rate=0.833), momentum=MomentumStats(current_win_streak=0, current_lose_streak=1, last_five_win_rate=0.8, momentum_score=-1.0), finishing=FinishingStats(ko_wins=6, submission_wins=0, decision_wins=4, finish_rate=0.6, ko_rate=0.6, submission_rate=0.0, decision_rate=0.4), striking=StrikingStats(average_sig_strikes=6.7, strike_accuracy=0.61, strike_defence=0.0, strike_differential=0.0), grappling=GrapplingStats(average_takedowns=0.29, takedown_accuracy=0.42, takedown_defence=0.0, average_submission_attempts=0.3), durability=DurabilityStats(average_fight_time=744.2, average_sig_strikes_absorbed=0.0), activity=ActivityStats(days_since_last_fight=109, fights_last_year=2))

In [21]:
print("=" * 60)
print("GLADIATOR AI - PRE FIGHT PROFILE")
print("=" * 60)

print(f"\nFighter: {profile.fighter}")
print(f"Snapshot: {profile.snapshot_date.date()}")

print("\nRECORD")
print(profile.record)

print("\nPHYSICAL")
print(profile.physical)

print("\nACTIVITY")
print(profile.activity)

print("\nMOMENTUM")
print(profile.momentum)

print("\nFINISHING")
print(profile.finishing)

print("\nSTRIKING")
print(profile.striking)

print("\nGRAPPLING")
print(profile.grappling)

print("\nDURABILITY")
print(profile.durability)

============================================================
GLADIATOR AI - PRE FIGHT PROFILE
============================================================

Fighter: Sean O'Malley
Snapshot: 2025-01-01

RECORD
RecordStats(wins=10, losses=2, draws=0, no_contests=0, total_fights=12, win_rate=0.833)

PHYSICAL
PhysicalStats(age=29.0, height=180.34, reach=182.88)

ACTIVITY
ActivityStats(days_since_last_fight=109, fights_last_year=2)

MOMENTUM
MomentumStats(current_win_streak=0, current_lose_streak=1, last_five_win_rate=0.8, momentum_score=-1.0)

FINISHING
FinishingStats(ko_wins=6, submission_wins=0, decision_wins=4, finish_rate=0.6, ko_rate=0.6, submission_rate=0.0, decision_rate=0.4)

STRIKING
StrikingStats(average_sig_strikes=6.7, strike_accuracy=0.61, strike_defence=0.0, strike_differential=0.0)

GRAPPLING
GrapplingStats(average_takedowns=0.29, takedown_accuracy=0.42, takedown_defence=0.0, average_submission_attempts=0.3)

DURABILITY
DurabilityStats(average_fight_time=744.2, average_sig_strikes_absorbed=0.0)

In [22]:
from database_builder import DatasetBuilder

builder = DatasetBuilder(df)

fight = df.iloc[100]

matchup, skipped = builder.build_fight(
    row_index=100,
    fight=fight,
)


print("MATCHUP")
print(matchup)


print()
print("SKIPPED")
print(skipped)

MATCHUP
MatchupProfile(red_fighter='Jonathan Micallef', blue_fighter='Oban Elliott', snapshot_date='2026-01-31', winner='Red', age_diff=-2.0, height_diff=0.0, reach_diff=12.700000000000017, experience_diff=-3.0, wins_diff=-2.0, losses_diff=-1.0, win_rate_diff=0.25, win_streak_diff=1.0, lose_streak_diff=-1.0, momentum_diff=2.0, ko_rate_diff=-0.333, submission_rate_diff=0.0, decision_rate_diff=0.33299999999999996, fight_time_diff=65.0, sig_strike_diff=0.33999999999999986, takedown_diff=-0.3900000000000001, submission_attempt_diff=1.1)

SKIPPED
None

In [23]:
import pandas as pd


# ============================================================
# GLADIATOR AI — SINGLE FIGHT PIPELINE VALIDATION
# ============================================================

# 1. Create the Dataset Builder
builder = DatasetBuilder(df)

# 2. Select ONE historical fight
row_index = 100
fight = df.iloc[row_index]

fight_date = pd.to_datetime(fight["date"])

print("=" * 70)
print("GLADIATOR AI — SINGLE FIGHT VALIDATION")
print("=" * 70)

print("\nSOURCE FIGHT")
print("-" * 70)

print(f"Row index : {row_index}")
print(f"Date      : {fight_date.date()}")
print(f"Red       : {fight['R_fighter']}")
print(f"Blue      : {fight['B_fighter']}")
print(f"Winner    : {fight['Winner']}")
print(f"Finish    : {fight['finish']}")


# ============================================================
# 3. Build ONE matchup
# ============================================================

matchup, skipped = builder.build_fight(
    row_index=row_index,
    fight=fight,
)


# ============================================================
# 4. Validate skipped status
# ============================================================

print("\nBUILD STATUS")
print("-" * 70)

print("Skipped:", skipped)

if skipped is not None:

    print("\n❌ FIGHT WAS SKIPPED")
    print("Reason:", skipped.reason)

else:

    print("✅ Fight successfully converted into a matchup")


# ============================================================
# 5. Stop immediately if no matchup was created
# ============================================================

if matchup is None:

    raise RuntimeError(
        "No MatchupProfile was created. "
        "The fight was skipped."
    )


# ============================================================
# 6. Print MatchupProfile
# ============================================================

print("\nMATCHUP PROFILE")
print("-" * 70)

print(matchup)


# ============================================================
# 7. Convert to dictionary
# ============================================================

matchup_dict = builder.matchup_engine.to_dict(
    matchup
)

print("\nMATCHUP DICTIONARY")
print("-" * 70)

print(matchup_dict)


# ============================================================
# 8. Convert to one-row DataFrame
# ============================================================

matchup_df = builder.matchup_engine.to_dataframe(
    matchup
)

print("\nMATCHUP DATAFRAME")
print("-" * 70)

print(matchup_df)

print("\nDataFrame shape:", matchup_df.shape)


# ============================================================
# 9. Validate the expected one-row structure
# ============================================================

assert len(matchup_df) == 1, (
    "Expected exactly one ML row."
)

assert matchup.red_fighter == fight["R_fighter"], (
    "Red fighter mismatch."
)

assert matchup.blue_fighter == fight["B_fighter"], (
    "Blue fighter mismatch."
)

assert matchup.winner == fight["Winner"], (
    "Winner mismatch."
)

assert matchup.snapshot_date == str(
    fight_date.date()
), (
    "Snapshot date mismatch."
)


# ============================================================
# 10. LEAKAGE TEST
# ============================================================

print("\nLEAKAGE CHECK")
print("-" * 70)

red_history = builder.history_engine.get_history(
    fighter=fight["R_fighter"],
    before_date=fight_date,
)

blue_history = builder.history_engine.get_history(
    fighter=fight["B_fighter"],
    before_date=fight_date,
)


# Red history must contain only earlier fights
if not red_history.empty:

    red_latest_date = pd.to_datetime(
        red_history["date"].iloc[0]
    )

    print(
        "Red latest historical fight:",
        red_latest_date.date()
    )

    assert red_latest_date < fight_date, (
        "LEAKAGE DETECTED: "
        "Red history contains the current fight."
    )

else:

    print("Red has no historical fights before this matchup.")


# Blue history must contain only earlier fights
if not blue_history.empty:

    blue_latest_date = pd.to_datetime(
        blue_history["date"].iloc[0]
    )

    print(
        "Blue latest historical fight:",
        blue_latest_date.date()
    )

    assert blue_latest_date < fight_date, (
        "LEAKAGE DETECTED: "
        "Blue history contains the current fight."
    )

else:

    print("Blue has no historical fights before this matchup.")


# ============================================================
# 11. Feature sanity checks
# ============================================================

print("\nFEATURE CHECK")
print("-" * 70)

feature_columns = [
    "age_diff",
    "height_diff",
    "reach_diff",
    "experience_diff",
    "wins_diff",
    "losses_diff",
    "win_rate_diff",
    "win_streak_diff",
    "lose_streak_diff",
    "momentum_diff",
    "ko_rate_diff",
    "submission_rate_diff",
    "decision_rate_diff",
    "fight_time_diff",
    "sig_strike_diff",
    "takedown_diff",
    "submission_attempt_diff",
]

for column in feature_columns:

    value = matchup_df.iloc[0][column]

    print(f"{column:28} {value}")

    assert pd.notna(value), (
        f"Feature '{column}' is missing."
    )


# ============================================================
# 12. FINAL RESULT
# ============================================================

print("\n" + "=" * 70)
print("✅ SINGLE-FIGHT PIPELINE VALIDATION PASSED")
print("=" * 70)

print(
    "\nOne historical UFC fight successfully became "
    "one leakage-checked ML training row."
)

print(
    "\nReady for full DatasetBuilder.build()."
)

======================================================================
GLADIATOR AI — SINGLE FIGHT VALIDATION
======================================================================

SOURCE FIGHT
----------------------------------------------------------------------
Row index : 100
Date      : 2026-01-31
Red       : Jonathan Micallef
Blue      : Oban Elliott
Winner    : Red
Finish    : SUB

BUILD STATUS
----------------------------------------------------------------------
Skipped: None
✅ Fight successfully converted into a matchup

MATCHUP PROFILE
----------------------------------------------------------------------
MatchupProfile(red_fighter='Jonathan Micallef', blue_fighter='Oban Elliott', snapshot_date='2026-01-31', winner='Red', age_diff=-2.0, height_diff=0.0, reach_diff=12.700000000000017, experience_diff=-3.0, wins_diff=-2.0, losses_diff=-1.0, win_rate_diff=0.25, win_streak_diff=1.0, lose_streak_diff=-1.0, momentum_diff=2.0, ko_rate_diff=-0.333, submission_rate_diff=0.0, decision_rate_diff=0.33299999999999996, fight_time_diff=65.0, sig_strike_diff=0.33999999999999986, takedown_diff=-0.3900000000000001, submission_attempt_diff=1.1)

MATCHUP DICTIONARY
----------------------------------------------------------------------
{'red_fighter': 'Jonathan Micallef', 'blue_fighter': 'Oban Elliott', 'snapshot_date': '2026-01-31', 'winner': 'Red', 'age_diff': -2.0, 'height_diff': 0.0, 'reach_diff': 12.700000000000017, 'experience_diff': -3.0, 'wins_diff': -2.0, 'losses_diff': -1.0, 'win_rate_diff': 0.25, 'win_streak_diff': 1.0, 'lose_streak_diff': -1.0, 'momentum_diff': 2.0, 'ko_rate_diff': -0.333, 'submission_rate_diff': 0.0, 'decision_rate_diff': 0.33299999999999996, 'fight_time_diff': 65.0, 'sig_strike_diff': 0.33999999999999986, 'takedown_diff': -0.3900000000000001, 'submission_attempt_diff': 1.1}

MATCHUP DATAFRAME
----------------------------------------------------------------------
         red_fighter  blue_fighter snapshot_date winner  age_diff  \
0  Jonathan Micallef  Oban Elliott    2026-01-31    Red      -2.0

   height_diff  reach_diff  experience_diff  wins_diff  losses_diff  ...  \
0          0.0        12.7             -3.0       -2.0         -1.0  ...

   win_streak_diff  lose_streak_diff  momentum_diff  ko_rate_diff  \
0              1.0              -1.0            2.0        -0.333

   submission_rate_diff  decision_rate_diff  fight_time_diff  sig_strike_diff  \
0                   0.0               0.333             65.0             0.34

   takedown_diff  submission_attempt_diff
0          -0.39                      1.1

[1 rows x 21 columns]

DataFrame shape: (1, 21)

LEAKAGE CHECK
----------------------------------------------------------------------
Red latest historical fight: 2025-02-08
Blue latest historical fight: 2025-06-21

FEATURE CHECK
----------------------------------------------------------------------
age_diff                     -2.0
height_diff                  0.0
reach_diff                   12.700000000000017
experience_diff              -3.0
wins_diff                    -2.0
losses_diff                  -1.0
win_rate_diff                0.25
win_streak_diff              1.0
lose_streak_diff             -1.0
momentum_diff                2.0
ko_rate_diff                 -0.333
submission_rate_diff         0.0
decision_rate_diff           0.33299999999999996
fight_time_diff              65.0
sig_strike_diff              0.33999999999999986
takedown_diff                -0.3900000000000001
submission_attempt_diff      1.1

======================================================================
✅ SINGLE-FIGHT PIPELINE VALIDATION PASSED
======================================================================

One historical UFC fight successfully became one leakage-checked ML training row.

Ready for full DatasetBuilder.build().

In [24]:
history = history_engine.get_history(
    fighter="John Smith",
    before_date="2025-01-01"
)

physical = PhysicalEngine().build(
    history,
    "John Smith"
)

print(physical)

PhysicalStats(age=nan, height=nan, reach=nan)

In [25]:
print(history.shape)

(0, 118)

In [26]:
print(history[["R_fighter", "B_fighter", "date"]].head())

Empty DataFrame
Columns: [R_fighter, B_fighter, date]
Index: []

In [27]:
# ============================================================
# GLADIATOR AI — FULL DATASET BUILD
# ============================================================


builder = DatasetBuilder(df)

print("=" * 70)
print("GLADIATOR AI — BUILDING FULL TRAINING DATASET")
print("=" * 70)

result = builder.build()

print("\nBUILD COMPLETE")
print("-" * 70)

print("Original fights :", len(df))
print("Generated rows  :", result.row_count)
print("Skipped fights  :", result.skipped_count)
print("Total processed :", result.total_processed)

print("\nDataset shape")
print("-" * 70)

print(result.rows.shape)

======================================================================
GLADIATOR AI — BUILDING FULL TRAINING DATASET
======================================================================

BUILD COMPLETE
----------------------------------------------------------------------
Original fights : 7177
Generated rows  : 7169
Skipped fights  : 8
Total processed : 7177

Dataset shape
----------------------------------------------------------------------
(7169, 21)

In [28]:
result.rows.head()

,red_fighter,blue_fighter,snapshot_date,winner,age_diff,height_diff,reach_diff,experience_diff,wins_diff,losses_diff,...,win_streak_diff,lose_streak_diff,momentum_diff,ko_rate_diff,submission_rate_diff,decision_rate_diff,fight_time_diff,sig_strike_diff,takedown_diff,submission_attempt_diff
0,Israel Adesanya,Joe Pyfer,2026-03-28,Blue,6.0,5.08,12.70,11.0,7.0,4.0,...,-3.0,3.0,-6.0,-0.115,-0.333,0.448,524.30,0.51,-1.40,-0.8
1,Alexa Grasso,Maycee Barber,2026-03-28,Red,4.0,0.00,2.54,1.0,-2.0,3.0,...,-7.0,2.0,-9.0,-0.400,0.250,0.025,187.91,-0.45,-1.16,0.6
2,Michael Chiesa,Niko Price,2026-03-28,Red,1.0,2.54,-2.54,3.0,6.0,-3.0,...,3.0,-3.0,6.0,-0.500,0.321,0.179,49.02,-3.09,2.05,0.4
3,Julian Erosa,Lerryan Douglas,2026-03-28,Blue,5.0,10.16,5.08,17.0,9.0,8.0,...,0.0,1.0,-1.0,0.222,0.444,0.333,511.88,6.18,1.73,0.7
4,Mansur Abdul-Malik,Yousri Belgaroui,2026-03-28,Blue,-5.0,-10.16,2.54,3.0,2.0,0.0,...,0.0,0.0,0.0,-0.333,0.333,0.000,-311.75,-2.82,1.36,0.3

In [29]:
result.rows.columns.tolist()

['red_fighter',
 'blue_fighter',
 'snapshot_date',
 'winner',
 'age_diff',
 'height_diff',
 'reach_diff',
 'experience_diff',
 'wins_diff',
 'losses_diff',
 'win_rate_diff',
 'win_streak_diff',
 'lose_streak_diff',
 'momentum_diff',
 'ko_rate_diff',
 'submission_rate_diff',
 'decision_rate_diff',
 'fight_time_diff',
 'sig_strike_diff',
 'takedown_diff',
 'submission_attempt_diff']

In [30]:
result.skipped[:10]

[SkippedFight(row_index=11, red_fighter='Ricky Simon', blue_fighter='Adrian Yanez', fight_date='2026-03-28', reason='Fight does not have a standard Red/Blue winner.'),
 SkippedFight(row_index=120, red_fighter='Kennedy Nzechukwu', blue_fighter='Marcus Buchecha', fight_date='2025-12-13', reason='Fight does not have a standard Red/Blue winner.'),
 SkippedFight(row_index=132, red_fighter='Jan Blachowicz', blue_fighter='Bogdan Guskov', fight_date='2025-12-06', reason='Fight does not have a standard Red/Blue winner.'),
 SkippedFight(row_index=195, red_fighter='Tom Aspinall', blue_fighter='Ciryl Gane', fight_date='2025-10-25', reason='Fight does not have a standard Red/Blue winner.'),
 SkippedFight(row_index=269, red_fighter='Zach Reese', blue_fighter='Sedriques Dumas', fight_date='2025-09-13', reason='Fight does not have a standard Red/Blue winner.'),
 SkippedFight(row_index=399, red_fighter='Mansur Abdul-Malik', blue_fighter='Cody Brundage', fight_date='2025-06-14', reason='Fight does not have a standard Red/Blue winner.'),
 SkippedFight(row_index=401, red_fighter='Paul Craig', blue_fighter='Rodolfo Bellato', fight_date='2025-06-14', reason='Fight does not have a standard Red/Blue winner.'),
 SkippedFight(row_index=589, red_fighter='Jimmy Crute', blue_fighter='Rodolfo Bellato', fight_date='2025-02-08', reason='Fight does not have a standard Red/Blue winner.')]

In [31]:
result.row_count + result.skipped_count == len(df)

True

In [32]:
assert result.total_processed == len(df)

print("✅ Every source fight was accounted for.")

✅ Every source fight was accounted for.

In [33]:
duplicate_count = result.rows.duplicated().sum()

print("Duplicate rows:", duplicate_count)

assert duplicate_count == 0

Duplicate rows: 0

In [34]:
missing_values = result.rows.isna().sum()

print(missing_values[missing_values > 0])

reach_diff    1
dtype: int64

In [35]:
print(
    result.rows["winner"].value_counts()
)

winner
Red     4145
Blue    3024
Name: count, dtype: int64

In [36]:
import pandas as pd

from feature_engine.history import HistoryEngine
from feature_engine.calculators.physical import PhysicalEngine
from feature_engine.models import PhysicalStats


# ============================================================
# GLADIATOR AI — PHYSICAL ENGINE VALIDATION
# ============================================================

history_engine = HistoryEngine(df)

# ------------------------------------------------------------
# Find a real fighter from the dataset
# ------------------------------------------------------------

red_fighters = df["R_fighter"].dropna().astype(str)
blue_fighters = df["B_fighter"].dropna().astype(str)

all_fighters = pd.concat(
    [red_fighters, blue_fighters],
    ignore_index=True,
)

fighter_counts = all_fighters.value_counts()

fighter = fighter_counts[
    fighter_counts >= 2
].index[0]


# ------------------------------------------------------------
# Get this fighter's fights
# ------------------------------------------------------------

fighter_fights = df[
    (df["R_fighter"] == fighter)
    | (df["B_fighter"] == fighter)
].copy()

fighter_fights["date"] = pd.to_datetime(
    fighter_fights["date"]
)

fighter_fights = fighter_fights.sort_values(
    "date"
)


# ------------------------------------------------------------
# Choose a snapshot after their previous fight
# ------------------------------------------------------------

snapshot_date = fighter_fights["date"].iloc[-1]

history = history_engine.get_history(
    fighter=fighter,
    before_date=snapshot_date,
)


# ------------------------------------------------------------
# Build physical profile
# ------------------------------------------------------------

physical_engine = PhysicalEngine()

physical = physical_engine.build(
    history=history,
    fighter=fighter,
)


# ============================================================
# RESULTS
# ============================================================

print("=" * 70)
print("GLADIATOR AI — PHYSICAL ENGINE VALIDATION")
print("=" * 70)

print(f"\nFighter       : {fighter}")
print(f"Snapshot date : {snapshot_date.date()}")
print(f"History rows  : {len(history)}")


print("\nLatest Historical Fight")
print("-" * 70)

if not history.empty:
    print(
        history[
            [
                "date",
                "R_fighter",
                "B_fighter",
            ]
        ].iloc[0]
    )


print("\nPhysical Profile")
print("-" * 70)

print(physical)


# ============================================================
# VALIDATION
# ============================================================

print("\nValidation")
print("-" * 70)

assert not history.empty, (
    "HistoryEngine returned no historical fights."
)

assert isinstance(
    physical,
    PhysicalStats,
), (
    "PhysicalEngine did not return PhysicalStats."
)

print("✅ HistoryEngine returned real historical data.")

print("✅ PhysicalEngine returned a valid PhysicalStats object.")

print("✅ Physical validation passed.")

======================================================================
GLADIATOR AI — PHYSICAL ENGINE VALIDATION
======================================================================

Fighter       : Jim Miller
Snapshot date : 2025-04-12
History rows  : 38

Latest Historical Fight
----------------------------------------------------------------------
date         2024-11-16 00:00:00
R_fighter             Jim Miller
B_fighter          Damon Jackson
Name: 0, dtype: object

Physical Profile
----------------------------------------------------------------------
PhysicalStats(age=41.0, height=172.72, reach=180.34)

Validation
----------------------------------------------------------------------
✅ HistoryEngine returned real historical data.
✅ PhysicalEngine returned a valid PhysicalStats object.
✅ Physical validation passed.

In [37]:

builder = DatasetBuilder(df)

result = builder.build()

print("Original fights :", len(df))
print("Generated rows  :", result.row_count)
print("Skipped fights  :", result.skipped_count)
print("Total processed :", result.total_processed)

Original fights : 7177
Generated rows  : 7169
Skipped fights  : 8
Total processed : 7177

In [38]:
result.rows[
    [
        "red_fighter",
        "blue_fighter",
        "age_diff",
        "height_diff",
        "reach_diff",
    ]
].head(20)

,red_fighter,blue_fighter,age_diff,height_diff,reach_diff
0,Israel Adesanya,Joe Pyfer,6.0,5.08,12.70
1,Alexa Grasso,Maycee Barber,4.0,0.00,2.54
2,Michael Chiesa,Niko Price,1.0,2.54,-2.54
3,Julian Erosa,Lerryan Douglas,5.0,10.16,5.08
4,Mansur Abdul-Malik,Yousri Belgaroui,-5.0,-10.16,2.54
5,Terrance McKinney,Kyle Nelson,-3.0,-2.54,5.08
6,Ignacio Bahamondes,Tofiq Musayev,-8.0,15.24,15.24
7,Chase Hooper,Lance Gibson Jr.,-5.0,10.16,5.08
8,Marcin Tybura,Tyrell Fortune,4.0,7.62,7.62
9,Casey O'Neill,Gabriella Fernandes,-5.0,0.00,7.62
10,Navajo Stirling,Bruno Lopes,-5.0,5.08,12.70
11,Alexia Thainara,Bruna Brasil,-3.0,-5.08,5.08
12,Movsar Evloev,Lerone Murphy,-4.0,-5.08,-2.54
13,Luke Riley,Michael Aswell Jr.,1.0,2.54,0.00
14,Michael Page,Sam Patterson,9.0,0.00,2.54
15,Iwo Baraniewski,Austen Lane,-10.0,-15.24,-17.78
16,Roman Dolidze,Christian Leroy Duncan,7.0,0.00,-7.62
17,Kurtis Campbell,Danny Silva,-5.0,5.08,7.62
18,Mason Jones,Axel Sola,3.0,-5.08,0.00
19,Nathaniel Wood,Losene Keita,4.0,-2.54,-7.62

In [39]:
result.rows[
    result.rows["height_diff"].abs() > 50
][
    [
        "red_fighter",
        "blue_fighter",
        "snapshot_date",
        "age_diff",
        "height_diff",
        "reach_diff",
    ]
]

Empty DataFrame
Columns: [red_fighter, blue_fighter, snapshot_date, age_diff, height_diff, reach_diff]
Index: []

In [40]:
from feature_engine.history import HistoryEngine
from feature_engine.calculators.physical import PhysicalEngine

history_engine = HistoryEngine(df)

fighter = "Julian Erosa"

history = history_engine.get_history(
    fighter=fighter,
    before_date="2026-03-28"
)

print("History rows:", len(history))

physical = PhysicalEngine().build(
    history=history,
    fighter=fighter
)

print(physical)

History rows: 17
PhysicalStats(age=35.0, height=185.42, reach=187.96)

In [41]:
from feature_engine.history import HistoryEngine
from feature_engine.calculators.physical import PhysicalEngine

history_engine = HistoryEngine(df)
physical_engine = PhysicalEngine()

fight_date = pd.Timestamp("2026-03-28")

red = "Julian Erosa"
blue = "Lerryan Douglas"

red_history = history_engine.get_history(
    fighter=red,
    before_date=fight_date,
)

blue_history = history_engine.get_history(
    fighter=blue,
    before_date=fight_date,
)

red_physical = physical_engine.build(
    history=red_history,
    fighter=red,
)

blue_physical = physical_engine.build(
    history=blue_history,
    fighter=blue,
)

print("=" * 70)
print("PHYSICAL FEATURE DEBUG")
print("=" * 70)

print("\nRED")
print("Fighter :", red)
print("History :", len(red_history))
print("Profile :", red_physical)

print("\nBLUE")
print("Fighter :", blue)
print("History :", len(blue_history))
print("Profile :", blue_physical)

print("\nRAW VALUES")
print("-" * 70)

print("Red height  :", red_physical.height)
print("Blue height :", blue_physical.height)

print("Red reach   :", red_physical.reach)
print("Blue reach  :", blue_physical.reach)

print("Red age     :", red_physical.age)
print("Blue age    :", blue_physical.age)

======================================================================
PHYSICAL FEATURE DEBUG
======================================================================

RED
Fighter : Julian Erosa
History : 17
Profile : PhysicalStats(age=35.0, height=185.42, reach=187.96)

BLUE
Fighter : Lerryan Douglas
History : 0
Profile : PhysicalStats(age=nan, height=nan, reach=nan)

RAW VALUES
----------------------------------------------------------------------
Red height  : 185.42
Blue height : nan
Red reach   : 187.96
Blue reach  : nan
Red age     : 35.0
Blue age    : nan

In [42]:

builder = DatasetBuilder(df)

fight = df.iloc[100]

matchup, skipped = builder.build_fight(
    row_index=100,
    fight=fight,
)

print(matchup)

MatchupProfile(red_fighter='Jonathan Micallef', blue_fighter='Oban Elliott', snapshot_date='2026-01-31', winner='Red', age_diff=-2.0, height_diff=0.0, reach_diff=12.700000000000017, experience_diff=-3.0, wins_diff=-2.0, losses_diff=-1.0, win_rate_diff=0.25, win_streak_diff=1.0, lose_streak_diff=-1.0, momentum_diff=2.0, ko_rate_diff=-0.333, submission_rate_diff=0.0, decision_rate_diff=0.33299999999999996, fight_time_diff=65.0, sig_strike_diff=0.33999999999999986, takedown_diff=-0.3900000000000001, submission_attempt_diff=1.1)

In [43]:
red_history = builder.history_engine.get_history(
    fighter=fight["R_fighter"],
    before_date=fight["date"],
)

blue_history = builder.history_engine.get_history(
    fighter=fight["B_fighter"],
    before_date=fight["date"],
)

red_profile = builder.profile_engine.build(
    history=red_history,
    fighter=fight["R_fighter"],
    snapshot_date=fight["date"],
    fallback_fight=fight,
)

blue_profile = builder.profile_engine.build(
    history=blue_history,
    fighter=fight["B_fighter"],
    snapshot_date=fight["date"],
    fallback_fight=fight,
)

print("RED PHYSICAL:")
print(red_profile.physical)

print()
print("BLUE PHYSICAL:")
print(blue_profile.physical)

RED PHYSICAL:
PhysicalStats(age=25.0, height=182.88, reach=195.58)

BLUE PHYSICAL:
PhysicalStats(age=27.0, height=182.88, reach=182.88)

In [44]:
import pandas as pd

row = df[
    (df["R_fighter"] == "Julian Erosa") &
    (df["B_fighter"] == "Lerryan Douglas")
].iloc[0]

builder = DatasetBuilder(df)

matchup, skipped = builder.build_fight(
    row_index=0,
    fight=row,
)

print("MATCHUP:")
print(matchup)

print()
print("SKIPPED:")
print(skipped)

MATCHUP:
MatchupProfile(red_fighter='Julian Erosa', blue_fighter='Lerryan Douglas', snapshot_date='2026-03-28', winner='Blue', age_diff=5.0, height_diff=10.159999999999997, reach_diff=5.0800000000000125, experience_diff=17.0, wins_diff=9.0, losses_diff=8.0, win_rate_diff=0.529, win_streak_diff=0.0, lose_streak_diff=1.0, momentum_diff=-1.0, ko_rate_diff=0.222, submission_rate_diff=0.444, decision_rate_diff=0.333, fight_time_diff=511.88, sig_strike_diff=6.18, takedown_diff=1.73, submission_attempt_diff=0.7)

SKIPPED:
None

In [45]:
red_history = builder.history_engine.get_history(
    fighter="Julian Erosa",
    before_date=row["date"],
)

blue_history = builder.history_engine.get_history(
    fighter="Lerryan Douglas",
    before_date=row["date"],
)

red_profile = builder.profile_engine.build(
    history=red_history,
    fighter="Julian Erosa",
    snapshot_date=row["date"],
    fallback_fight=row,
)

blue_profile = builder.profile_engine.build(
    history=blue_history,
    fighter="Lerryan Douglas",
    snapshot_date=row["date"],
    fallback_fight=row,
)

print("RED:")
print(red_profile.physical)

print()
print("BLUE:")
print(blue_profile.physical)

RED:
PhysicalStats(age=35.0, height=185.42, reach=187.96)

BLUE:
PhysicalStats(age=30.0, height=175.26, reach=182.88)

In [46]:
print(matchup)

MatchupProfile(red_fighter='Julian Erosa', blue_fighter='Lerryan Douglas', snapshot_date='2026-03-28', winner='Blue', age_diff=5.0, height_diff=10.159999999999997, reach_diff=5.0800000000000125, experience_diff=17.0, wins_diff=9.0, losses_diff=8.0, win_rate_diff=0.529, win_streak_diff=0.0, lose_streak_diff=1.0, momentum_diff=-1.0, ko_rate_diff=0.222, submission_rate_diff=0.444, decision_rate_diff=0.333, fight_time_diff=511.88, sig_strike_diff=6.18, takedown_diff=1.73, submission_attempt_diff=0.7)

In [47]:

builder = DatasetBuilder(df)

result = builder.build()

print("=" * 70)
print("GLADIATOR AI — FINAL DATASET BUILD")
print("=" * 70)

print(f"Original fights : {len(df)}")
print(f"Generated rows  : {result.row_count}")
print(f"Skipped fights  : {result.skipped_count}")
print(f"Total processed : {result.total_processed}")

======================================================================
GLADIATOR AI — FINAL DATASET BUILD
======================================================================
Original fights : 7177
Generated rows  : 7169
Skipped fights  : 8
Total processed : 7177

In [48]:
assert (
    result.row_count +
    result.skipped_count
) == len(df)

print("✅ Every source fight accounted for.")

✅ Every source fight accounted for.

In [49]:
physical_check = result.rows[
    [
        "age_diff",
        "height_diff",
        "reach_diff",
    ]
]

print("Missing values:")
print(physical_check.isna().sum())

print("\nImpossible height differences:")
print(
    result.rows[
        result.rows["height_diff"].abs() > 50
    ][
        [
            "red_fighter",
            "blue_fighter",
            "snapshot_date",
            "age_diff",
            "height_diff",
            "reach_diff",
        ]
    ]
)

Missing values:
age_diff       0
height_diff    0
reach_diff     1
dtype: int64

Impossible height differences:
Empty DataFrame
Columns: [red_fighter, blue_fighter, snapshot_date, age_diff, height_diff, reach_diff]
Index: []

In [50]:
print("\nImpossible reach differences:")
print(
    result.rows[
        result.rows["reach_diff"].abs() > 60
    ][
        [
            "red_fighter",
            "blue_fighter",
            "snapshot_date",
            "age_diff",
            "height_diff",
            "reach_diff",
        ]
    ]
)

Impossible reach differences:
Empty DataFrame
Columns: [red_fighter, blue_fighter, snapshot_date, age_diff, height_diff, reach_diff]
Index: []

In [51]:
# from pathlib import Path

# output_path = Path(
#     "datasets/processed/gladiator_training.csv"
# )

# output_path.parent.mkdir(
#     parents=True,
#     exist_ok=True
# )

# result.rows.to_csv(
#     output_path,
#     index=False
# )

# print(
#     f"✅ Dataset saved to: {output_path}"
# )

In [52]:

builder = DatasetBuilder(df)

for red, blue, date in [
    (
        "Irwin Rivera",
        "Ali Qaisi",
        "2020-08-08",
    ),
    (
        "Giga Chikadze",
        "Irwin Rivera",
        "2020-05-16",
    ),
]:

    row = df[
        (df["R_fighter"] == red)
        & (df["B_fighter"] == blue)
        & (
            pd.to_datetime(df["date"])
            == pd.to_datetime(date)
        )
    ].iloc[0]

    matchup, skipped = builder.build_fight(
        row_index=0,
        fight=row,
    )

    print("\n", red, "vs", blue)
    print("Reach difference:", matchup.reach_diff)

 Irwin Rivera vs Ali Qaisi
Reach difference: 0.0

 Giga Chikadze vs Irwin Rivera
Reach difference: nan

In [53]:
import pandas as pd
import numpy as np


# ============================================================
# GLADIATOR AI — PHYSICAL DATA QUALITY AUDIT
# ============================================================

physical_columns = [
    "R_age",
    "B_age",
    "R_Height_cms",
    "B_Height_cms",
    "R_Reach_cms",
    "B_Reach_cms",
]

print("=" * 80)
print("GLADIATOR AI — RAW PHYSICAL DATA AUDIT")
print("=" * 80)


# ------------------------------------------------------------
# 1. Missing values in the RAW dataset
# ------------------------------------------------------------

print("\nRAW MISSING VALUES")
print("-" * 80)

raw_missing = df[physical_columns].isna().sum()

print(raw_missing)


# ------------------------------------------------------------
# 2. Zero values in the RAW dataset
# ------------------------------------------------------------

print("\nRAW ZERO VALUES")
print("-" * 80)

raw_zeros = (
    df[physical_columns] == 0
).sum()

print(raw_zeros)


# ------------------------------------------------------------
# 3. Extremely suspicious physical values
# ------------------------------------------------------------

print("\nSUSPICIOUS RAW VALUES")
print("-" * 80)

for column in physical_columns:

    values = pd.to_numeric(
        df[column],
        errors="coerce"
    )

    suspicious = df[
        (values <= 0)
        |
        (values > 250)
    ]

    if not suspicious.empty:

        print(
            f"\n{column}: "
            f"{len(suspicious)} suspicious rows"
        )

        print(
            suspicious[
                [
                    "date",
                    "R_fighter",
                    "B_fighter",
                    column,
                ]
            ].head(10)
        )


# ------------------------------------------------------------
# 4. Missingness by physical category
# ------------------------------------------------------------

print("\nPHYSICAL MISSINGNESS BY CATEGORY")
print("-" * 80)

print(
    "Age missing:",
    df[
        ["R_age", "B_age"]
    ].isna().any(axis=1).sum()
)

print(
    "Height missing:",
    df[
        ["R_Height_cms", "B_Height_cms"]
    ].isna().any(axis=1).sum()
)

print(
    "Reach missing:",
    df[
        ["R_Reach_cms", "B_Reach_cms"]
    ].isna().any(axis=1).sum()
)


# ------------------------------------------------------------
# 5. Check whether zero is being used as missing
# ------------------------------------------------------------

print("\nZERO-AS-MISSING CHECK")
print("-" * 80)

for column in [
    "R_Height_cms",
    "B_Height_cms",
    "R_Reach_cms",
    "B_Reach_cms",
]:

    zero_count = (
        pd.to_numeric(
            df[column],
            errors="coerce"
        )
        .eq(0)
        .sum()
    )

    missing_count = df[column].isna().sum()

    print(
        f"{column:18}"
        f" missing={missing_count:<6}"
        f" zero={zero_count}"
    )


print("\n" + "=" * 80)
print("AUDIT COMPLETE")
print("=" * 80)

================================================================================
GLADIATOR AI — RAW PHYSICAL DATA AUDIT
================================================================================

RAW MISSING VALUES
--------------------------------------------------------------------------------
R_age           0
B_age           0
R_Height_cms    0
B_Height_cms    0
R_Reach_cms     0
B_Reach_cms     0
dtype: int64

RAW ZERO VALUES
--------------------------------------------------------------------------------
R_age           0
B_age           0
R_Height_cms    0
B_Height_cms    0
R_Reach_cms     0
B_Reach_cms     1
dtype: int64

SUSPICIOUS RAW VALUES
--------------------------------------------------------------------------------

B_Reach_cms: 1 suspicious rows
            date      R_fighter     B_fighter  B_Reach_cms
2984  2020-05-16  Giga Chikadze  Irwin Rivera          0.0

PHYSICAL MISSINGNESS BY CATEGORY
--------------------------------------------------------------------------------
Age missing: 0
Height missing: 0
Reach missing: 0

ZERO-AS-MISSING CHECK
--------------------------------------------------------------------------------
R_Height_cms       missing=0      zero=0
B_Height_cms       missing=0      zero=0
R_Reach_cms        missing=0      zero=0
B_Reach_cms        missing=0      zero=1

================================================================================
AUDIT COMPLETE
================================================================================

In [54]:
import pandas as pd

# ============================================================
# FIND ALL EXTREME REACH DIFFERENCES
# ============================================================

bad = result.rows[
    result.rows["reach_diff"].abs() > 60
].copy()

print("Bad matchup rows:", len(bad))

print(
    bad[
        [
            "red_fighter",
            "blue_fighter",
            "snapshot_date",
            "reach_diff",
        ]
    ].to_string(index=True)
)

Bad matchup rows: 0
Empty DataFrame
Columns: [red_fighter, blue_fighter, snapshot_date, reach_diff]
Index: []

In [56]:
# ============================================================
# TRACE THE SOURCE DATA FOR EACH BAD MATCHUP
# ============================================================

history_engine = HistoryEngine(df)
physical_engine = PhysicalEngine()

for _, bad_row in bad.iterrows():

    red = bad_row["red_fighter"]
    blue = bad_row["blue_fighter"]
    fight_date = pd.to_datetime(
        bad_row["snapshot_date"]
    )

    print("\n" + "=" * 80)
    print(f"{red} vs {blue} | {fight_date.date()}")
    print("=" * 80)

    # Find the actual source fight
    source = df[
        (df["R_fighter"] == red)
        & (df["B_fighter"] == blue)
        & (
            pd.to_datetime(df["date"])
            == fight_date
        )
    ]

    if source.empty:
        print("Source fight not found.")
        continue

    fight = source.iloc[0]

    print("\nCURRENT FIGHT ROW")
    print("-" * 80)
    print(
        fight[
            [
                "R_fighter",
                "B_fighter",
                "date",
                "R_Reach_cms",
                "B_Reach_cms",
            ]
        ]
    )

    red_history = history_engine.get_history(
        fighter=red,
        before_date=fight_date,
    )

    blue_history = history_engine.get_history(
        fighter=blue,
        before_date=fight_date,
    )

    red_profile = physical_engine.build(
        history=red_history,
        fighter=red,
        fallback_fight=fight,
    )

    blue_profile = physical_engine.build(
        history=blue_history,
        fighter=blue,
        fallback_fight=fight,
    )

    print("\nPROFILES")
    print("-" * 80)
    print("Red :", red_profile)
    print("Blue:", blue_profile)

    print("\nEXPECTED REACH DIFFERENCE")
    print("-" * 80)

    if pd.isna(red_profile.reach) or pd.isna(
        blue_profile.reach
    ):
        print("NaN — one reach is unavailable")
    else:
        print(
            red_profile.reach
            - blue_profile.reach
        )

In [57]:

builder = DatasetBuilder(df)

row = df[
    (df["R_fighter"] == "Irwin Rivera")
    & (df["B_fighter"] == "Ali Qaisi")
    & (
        pd.to_datetime(df["date"])
        == pd.Timestamp("2020-08-08")
    )
].iloc[0]

matchup, skipped = builder.build_fight(
    row_index=0,
    fight=row,
)

print(matchup)

MatchupProfile(red_fighter='Irwin Rivera', blue_fighter='Ali Qaisi', snapshot_date='2020-08-08', winner='Red', age_diff=2.0, height_diff=-5.0800000000000125, reach_diff=0.0, experience_diff=1.0, wins_diff=0.0, losses_diff=1.0, win_rate_diff=0.0, win_streak_diff=0.0, lose_streak_diff=1.0, momentum_diff=-1.0, ko_rate_diff=0.0, submission_rate_diff=0.0, decision_rate_diff=0.0, fight_time_diff=900.0, sig_strike_diff=2.27, takedown_diff=0.0, submission_attempt_diff=0.0)

In [58]:
row = df[
    (df["R_fighter"] == "Giga Chikadze")
    & (df["B_fighter"] == "Irwin Rivera")
    & (
        pd.to_datetime(df["date"])
        == pd.Timestamp("2020-05-16")
    )
].iloc[0]

matchup, skipped = builder.build_fight(
    row_index=0,
    fight=row,
)

print(matchup)

MatchupProfile(red_fighter='Giga Chikadze', blue_fighter='Irwin Rivera', snapshot_date='2020-05-16', winner='Red', age_diff=0.0, height_diff=15.240000000000009, reach_diff=nan, experience_diff=2.0, wins_diff=2.0, losses_diff=0.0, win_rate_diff=1.0, win_streak_diff=2.0, lose_streak_diff=0.0, momentum_diff=2.0, ko_rate_diff=0.0, submission_rate_diff=0.0, decision_rate_diff=1.0, fight_time_diff=900.0, sig_strike_diff=3.33, takedown_diff=0.51, submission_attempt_diff=0.0)

In [59]:
result = builder.build()

print("Original:", len(df))
print("Generated:", result.row_count)
print("Skipped:", result.skipped_count)

Original: 7177
Generated: 7169
Skipped: 8

In [60]:
print(
    result.rows[
        [
            "age_diff",
            "height_diff",
            "reach_diff",
        ]
    ].isna().sum()
)

age_diff       0
height_diff    0
reach_diff     1
dtype: int64

In [61]:
print(
    "Extreme height differences:",
    (result.rows["height_diff"].abs() > 50).sum()
)

print(
    "Extreme reach differences:",
    (result.rows["reach_diff"].abs() > 60).sum()
)

Extreme height differences: 0
Extreme reach differences: 0

In [62]:
# ============================================================
# GLADIATOR AI — FINAL DATASET VALIDATION
# ============================================================

import pandas as pd


print("=" * 80)
print("GLADIATOR AI — FINAL DATASET VALIDATION")
print("=" * 80)


# ============================================================
# 1. BASIC DATASET SUMMARY
# ============================================================

print("\nDATASET SUMMARY")
print("-" * 80)

print("Original fights :", len(df))
print("Generated rows  :", result.row_count)
print("Skipped fights  :", result.skipped_count)
print("Total processed :", result.total_processed)
print("Dataset shape   :", result.rows.shape)

assert (
    result.total_processed == len(df)
), "Not every source fight was accounted for."


# ============================================================
# 2. DUPLICATES
# ============================================================

duplicate_count = result.rows.duplicated().sum()

print("\nDUPLICATES")
print("-" * 80)
print("Duplicate rows:", duplicate_count)

assert duplicate_count == 0, (
    "Duplicate training rows detected."
)


# ============================================================
# 3. MISSING VALUES
# ============================================================

missing = result.rows.isna().sum()

print("\nMISSING VALUES")
print("-" * 80)

print(
    missing[
        missing > 0
    ]
)

# We expect reach_diff may contain a legitimate
# missing value. We inspect it rather than
# silently filling it.


# ============================================================
# 4. WINNER DISTRIBUTION
# ============================================================

winner_counts = (
    result.rows["winner"]
    .value_counts()
)

print("\nWINNER DISTRIBUTION")
print("-" * 80)

print(winner_counts)

assert set(
    result.rows["winner"].unique()
).issubset(
    {"Red", "Blue"}
), "Unexpected winner label detected."


# ============================================================
# 5. PHYSICAL FEATURE SANITY
# ============================================================

print("\nPHYSICAL FEATURE CHECK")
print("-" * 80)

extreme_age = (
    result.rows["age_diff"].abs() > 25
).sum()

extreme_height = (
    result.rows["height_diff"].abs() > 50
).sum()

extreme_reach = (
    result.rows["reach_diff"].abs() > 60
).sum()

print(
    "Extreme age differences   :",
    extreme_age
)

print(
    "Extreme height differences:",
    extreme_height
)

print(
    "Extreme reach differences :",
    extreme_reach
)

assert extreme_height == 0, (
    "Impossible height differences detected."
)

assert extreme_reach == 0, (
    "Impossible reach differences detected."
)


# ============================================================
# 6. RATE FEATURE SANITY
# ============================================================

print("\nRATE FEATURE CHECK")
print("-" * 80)

rate_columns = [
    "win_rate_diff",
    "ko_rate_diff",
    "submission_rate_diff",
    "decision_rate_diff",
]

for column in rate_columns:

    invalid = (
        result.rows[column].abs() > 1
    ).sum()

    print(
        f"{column:25} invalid: {invalid}"
    )

    assert invalid == 0, (
        f"Invalid values found in {column}."
    )


# ============================================================
# 7. DATASET FEATURE COUNT
# ============================================================

print("\nFEATURE COUNT")
print("-" * 80)

print(
    "Columns:",
    len(result.rows.columns)
)

print(
    result.rows.columns.tolist()
)


# ============================================================
# 8. SKIPPED FIGHTS
# ============================================================

print("\nSKIPPED FIGHTS")
print("-" * 80)

print(
    "Skipped:",
    result.skipped_count
)

if result.skipped:
    print("\nFirst skipped fights:")

    for skipped in result.skipped[:10]:

        print(
            skipped
        )


# ============================================================
# 9. FINAL CHECK
# ============================================================

print("\n" + "=" * 80)
print("✅ DATASET VALIDATION COMPLETE")
print("=" * 80)

print(
    "\nThe dataset passed the current structural,"
    " duplication, label, and physical sanity checks."
)

================================================================================
GLADIATOR AI — FINAL DATASET VALIDATION
================================================================================

DATASET SUMMARY
--------------------------------------------------------------------------------
Original fights : 7177
Generated rows  : 7169
Skipped fights  : 8
Total processed : 7177
Dataset shape   : (7169, 21)

DUPLICATES
--------------------------------------------------------------------------------
Duplicate rows: 0

MISSING VALUES
--------------------------------------------------------------------------------
reach_diff    1
dtype: int64

WINNER DISTRIBUTION
--------------------------------------------------------------------------------
winner
Red     4145
Blue    3024
Name: count, dtype: int64

PHYSICAL FEATURE CHECK
--------------------------------------------------------------------------------
Extreme age differences   : 0
Extreme height differences: 0
Extreme reach differences : 0

RATE FEATURE CHECK
--------------------------------------------------------------------------------
win_rate_diff             invalid: 0
ko_rate_diff              invalid: 0
submission_rate_diff      invalid: 0
decision_rate_diff        invalid: 0

FEATURE COUNT
--------------------------------------------------------------------------------
Columns: 21
['red_fighter', 'blue_fighter', 'snapshot_date', 'winner', 'age_diff', 'height_diff', 'reach_diff', 'experience_diff', 'wins_diff', 'losses_diff', 'win_rate_diff', 'win_streak_diff', 'lose_streak_diff', 'momentum_diff', 'ko_rate_diff', 'submission_rate_diff', 'decision_rate_diff', 'fight_time_diff', 'sig_strike_diff', 'takedown_diff', 'submission_attempt_diff']

SKIPPED FIGHTS
--------------------------------------------------------------------------------
Skipped: 8

First skipped fights:
SkippedFight(row_index=11, red_fighter='Ricky Simon', blue_fighter='Adrian Yanez', fight_date='2026-03-28', reason='Fight does not have a standard Red/Blue winner.')
SkippedFight(row_index=120, red_fighter='Kennedy Nzechukwu', blue_fighter='Marcus Buchecha', fight_date='2025-12-13', reason='Fight does not have a standard Red/Blue winner.')
SkippedFight(row_index=132, red_fighter='Jan Blachowicz', blue_fighter='Bogdan Guskov', fight_date='2025-12-06', reason='Fight does not have a standard Red/Blue winner.')
SkippedFight(row_index=195, red_fighter='Tom Aspinall', blue_fighter='Ciryl Gane', fight_date='2025-10-25', reason='Fight does not have a standard Red/Blue winner.')
SkippedFight(row_index=269, red_fighter='Zach Reese', blue_fighter='Sedriques Dumas', fight_date='2025-09-13', reason='Fight does not have a standard Red/Blue winner.')
SkippedFight(row_index=399, red_fighter='Mansur Abdul-Malik', blue_fighter='Cody Brundage', fight_date='2025-06-14', reason='Fight does not have a standard Red/Blue winner.')
SkippedFight(row_index=401, red_fighter='Paul Craig', blue_fighter='Rodolfo Bellato', fight_date='2025-06-14', reason='Fight does not have a standard Red/Blue winner.')
SkippedFight(row_index=589, red_fighter='Jimmy Crute', blue_fighter='Rodolfo Bellato', fight_date='2025-02-08', reason='Fight does not have a standard Red/Blue winner.')

================================================================================
✅ DATASET VALIDATION COMPLETE
================================================================================

The dataset passed the current structural, duplication, label, and physical sanity checks.

In [63]:
# ============================================================
# GLADIATOR AI — SAVE VALIDATED DATASET
# ============================================================

from pathlib import Path


output_path = Path(
    "datasets/processed/gladiator_training.csv"
)

# Make sure the destination exists
output_path.parent.mkdir(
    parents=True,
    exist_ok=True
)

# Overwrite the previous version
result.rows.to_csv(
    output_path,
    index=False
)

print("=" * 70)
print("GLADIATOR AI — DATASET SAVED")
print("=" * 70)

print(f"\nFile: {output_path}")
print(f"Rows: {len(result.rows)}")
print(f"Columns: {len(result.rows.columns)}")
print(
    f"Size: {output_path.stat().st_size / 1024:.2f} KB"
)

======================================================================
GLADIATOR AI — DATASET SAVED
======================================================================

File: datasets\processed\gladiator_training.csv
Rows: 7169
Columns: 21
Size: 1236.24 KB

In [64]:
import pandas as pd

saved = pd.read_csv(
    "datasets/processed/gladiator_training.csv"
)

print(saved.shape)
print(saved.head())

(7169, 21)
          red_fighter      blue_fighter snapshot_date winner  age_diff  \
0     Israel Adesanya         Joe Pyfer    2026-03-28   Blue       6.0
1        Alexa Grasso     Maycee Barber    2026-03-28    Red       4.0
2      Michael Chiesa        Niko Price    2026-03-28    Red       1.0
3        Julian Erosa   Lerryan Douglas    2026-03-28   Blue       5.0
4  Mansur Abdul-Malik  Yousri Belgaroui    2026-03-28   Blue      -5.0

   height_diff  reach_diff  experience_diff  wins_diff  losses_diff  ...  \
0         5.08       12.70             11.0        7.0          4.0  ...
1         0.00        2.54              1.0       -2.0          3.0  ...
2         2.54       -2.54              3.0        6.0         -3.0  ...
3        10.16        5.08             17.0        9.0          8.0  ...
4       -10.16        2.54              3.0        2.0          0.0  ...

   win_streak_diff  lose_streak_diff  momentum_diff  ko_rate_diff  \
0             -3.0               3.0           -6.0        -0.115
1             -7.0               2.0           -9.0        -0.400
2              3.0              -3.0            6.0        -0.500
3              0.0               1.0           -1.0         0.222
4              0.0               0.0            0.0        -0.333

   submission_rate_diff  decision_rate_diff  fight_time_diff  sig_strike_diff  \
0                -0.333               0.448           524.30             0.51
1                 0.250               0.025           187.91            -0.45
2                 0.321               0.179            49.02            -3.09
3                 0.444               0.333           511.88             6.18
4                 0.333               0.000          -311.75            -2.82

   takedown_diff  submission_attempt_diff
0          -1.40                     -0.8
1          -1.16                      0.6
2           2.05                      0.4
3           1.73                      0.7
4           1.36                      0.3

[5 rows x 21 columns]

In [65]:
# ============================================================
# CHECK UPCOMING FIGHTERS IN GLADIATOR AI DATA
# ============================================================

fighters_to_check = [
    "Anthony Hernandez",
    "Gregory Rodrigues",
]

for fighter in fighters_to_check:

    red_count = (
        df["R_fighter"] == fighter
    ).sum()

    blue_count = (
        df["B_fighter"] == fighter
    ).sum()

    total = red_count + blue_count

    print("=" * 60)
    print(fighter)
    print("=" * 60)
    print(f"Red appearances : {red_count}")
    print(f"Blue appearances: {blue_count}")
    print(f"Total fights    : {total}")

    if total > 0:
        print("✅ Fighter exists in historical dataset.")
    else:
        print("❌ Fighter is NOT in historical dataset.")

============================================================
Anthony Hernandez
============================================================
Red appearances : 4
Blue appearances: 8
Total fights    : 12
✅ Fighter exists in historical dataset.
============================================================
Gregory Rodrigues
============================================================
Red appearances : 3
Blue appearances: 10
Total fights    : 13
✅ Fighter exists in historical dataset.